return {
	"luckasRanarison/nvim-devdocs",
	branch = "master",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope.nvim",
		"nvim-treesitter/nvim-treesitter",
	},
	cmd = {
		"DevdocsFetch",
		"DevdocsInstall",
		"DevdocsUninstall",
		"DevdocsOpen",
		"DevdocsOpenFloat",
		"DevdocsOpenCurrent",
		"DevdocsOpenCurrentFloat",
		"DevdocsUpdate",
		"DevdocsUpdateAll",
		"DevdocsBuild",
	},
	opts = {
		format = "glow",
		filetypes = {
			javascript = { "html", "javascript" },
			ruby = { "ruby", "rails" }
		},
		-- use_node = false,
		ensure_installed = {
			-- "ruby",
			-- "rails",
			-- "git",
			-- "bash",
			-- "zig",
			-- "lua-5.1",
			-- "html",
			-- "css",
			-- "javascript",
			-- "typescript",
			-- "react",
			-- "web_extensions",
		},
		wrap = true,
		previewer_cmd = "glow",
		cmd_args = { "-s", "auto", "-w", "97" },
		cmd_ignore = {},
		picker_cmd = true,
		picker_cmd_args = { "-s", "auto", "-w", "45" },
		mappings = {
			open_in_browser = "<leader>OPEN",
			toggle_rendering = "<leader>|",
		},
		log_level = "debug",
	},
}
